# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import log_search_pb2 as log__search__pb2


class LogSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogs = channel.unary_unary(
                '/LogSearch/GetLogs',
                request_serializer=log__search__pb2.QueryParams.SerializeToString,
                response_deserializer=log__search__pb2.Response.FromString,
                )


class LogSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=log__search__pb2.QueryParams.FromString,
                    response_serializer=log__search__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LogSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LogSearch/GetLogs',
            log__search__pb2.QueryParams.SerializeToString,
            log__search__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
